export const communes = [
  { id: 5, nom: "Gombe", weight: 12 },
  { id: 11, nom: "Lingwala", weight: 10 },
  { id: 7, nom: "Kinshasa", weight: 9 },
  { id: 10, nom: "Limete", weight: 8 },
  { id: 9, nom: "Lemba", weight: 8 },
  { id: 18, nom: "Ngaliema", weight: 7 },
  { id: 14, nom: "Masina", weight: 10 },
  { id: 6, nom: "Kimbanseke", weight: 11 },
  { id: 23, nom: "Ndjili", weight: 10 },
  { id: 22, nom: "Kisenso", weight: 6 },
  { id: 12, nom: "Makala", weight: 6 },
  { id: 17, nom: "Ngaba", weight: 5 },
  { id: 2, nom: "Bumbu", weight: 5 },
  { id: 21, nom: "Selembao", weight: 5 },
  { id: 16, nom: "Mont Ngafula", weight: 4 },
  { id: 20, nom: "Nsele", weight: 3 },
  { id: 13, nom: "Maluku", weight: 2 },
  { id: 1, nom: "Bandalungwa", weight: 6 },
  { id: 4, nom: "Kasa-Vubu", weight: 7 },
  { id: 8, nom: "Kintambo", weight: 6 },
  { id: 19, nom: "Ngiri-Ngiri", weight: 5 },
  { id: 3, nom: "Kalamu", weight: 7 },
  { id: 24, nom: "Barumbu", weight: 6 }
]