export const communes = [
  { id: 1, nom: "Anderlecht", weight: 10 },
  { id: 2, nom: "Auderghem", weight: 8 },
  { id: 3, nom: "Berchem-Sainte-Agathe", weight: 6 },
  { id: 4, nom: "Bruxelles-Ville", weight: 12 },
  { id: 5, nom: "Etterbeek", weight: 9 },
  { id: 6, nom: "Evere", weight: 8 },
  { id: 7, nom: "Forest", weight: 9 },
  { id: 8, nom: "Ganshoren", weight: 6 },
  { id: 9, nom: "Ixelles", weight: 11 },
  { id: 10, nom: "Jette", weight: 8 },
  { id: 11, nom: "Koekelberg", weight: 6 },
  { id: 12, nom: "Molenbeek-Saint-Jean", weight: 10 },
  { id: 13, nom: "Saint-Gilles", weight: 9 },
  { id: 14, nom: "Saint-Josse-ten-Noode", weight: 7 },
  { id: 15, nom: "Schaerbeek", weight: 11 },
  { id: 16, nom: "Uccle", weight: 10 },
  { id: 17, nom: "Watermael-Boitsfort", weight: 7 },
  { id: 18, nom: "Woluwe-Saint-Lambert", weight: 10 },
  { id: 19, nom: "Woluwe-Saint-Pierre", weight: 9 }
];